version: "3.3"

services:

  elasticsearch:
    container_name: elasticsearch 
    image: elasticsearch:${ELK_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/user/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    networks:
      - elk-network

  logstash:
    container_name: logstash
    image: logstash:${ELK_VERSION} 
    volumes:
      - ./logstash/config:/usr/share/logstash/config:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5000:5000
      - 9600:9600
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
    networks:
      - elk-network
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: kibana:${ELK_VERSION}
    ports:
      - 5601:5601
    networks:
      - elk-network
    depends_on:
      - elasticsearch

networks:
  elk-network:
    driver: bridge
